### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by drupol** [crpeck/cas-overlay-docker#2]
Hi,

I'm trying your repo to have a simple CAS server locally and I'm having issue while the build:
```
Adding debian:COMODO_RSA_Certification_Authority.pem
Adding debian:GeoTrust_Universal_CA.pem
done.
Setting up junit4 (4.12-8) ...
Setting up groovy (2.4.16-2) ...
update-alternatives: using /usr/share/groovy/bin/groovy to provide /usr/bin/groovy (groovy) in auto mode
update-alternatives: error: error creating symbolic link '/usr/share/man/man1/groovy.1.gz.dpkg-tmp': No such file or directory
dpkg: error processing package groovy (--configure):
 installed groovy package post-installation script subprocess returned error exit status 2
Setting up ant-optional (1.10.5-2) ...
Setting up bnd (3.5.0-4) ...
dpkg: dependency problems prevent configuration of libgradle-core-java:
 libgradle-core-java depends on groovy (>= 2.4.7); however:
  Package groovy is not configured yet.

dpkg: error processing package libgradle-core-java (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgradle-plugins-java:
 libgradle-plugins-java depends on libgradle-core-java (>= 4.4.1-6); however:
  Package libgradle-core-java is not configured yet.

dpkg: error processing package libgradle-plugins-java (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gradle:
 gradle depends on libgradle-core-java (>= 4.4.1-6); however:
  Package libgradle-core-java is not configured yet.
 gradle depends on libgradle-plugins-java (>= 4.4.1-6); however:
  Package libgradle-plugins-java is not configured yet.

dpkg: error processing package gradle (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.28-10) ...
Processing triggers for ca-certificates (20190110) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Errors were encountered while processing:
 openjdk-11-jre-headless:amd64
 groovy
 libgradle-core-java
 libgradle-plugins-java
 gradle
E: Sub-process /usr/bin/dpkg returned an error code (1)
ERROR: Service 'cas' failed to build: The command '/bin/sh -c cd /tmp   && apt-get update   && apt-get install -y --no-install-recommends git gradle   && git clone -b master --single-branch https://github.com/apereo/cas-overlay-template.git cas-overlay   && mkdir -p /tmp/cas-overlay/src/main/webapp' returned a non-zero code: 100
$
```

**Comment by crpeck** [comment]
It looks like there was an issue between versions, I just did a clean run
'docker-compose up' and it worked fine. Can you retry it again?

**Comment by crpeck** [comment]
I'm going out of town for 2 weeks, but, it looks like the github repo for cas-overlay-template by Apereo at https://github.com/apereo/cas-overlay-template supports what you need.

**Comment by drupol** [comment]
> I'm going out of town for 2 weeks, but, it looks like the github repo for cas-overlay-template by Apereo at https://github.com/apereo/cas-overlay-template supports what you need.

I don't know if this is what I'm looking for.

All I'm looking for is a simple docker instance where I can have a CAS server.

Going to retry the docker-compose up in a couple of hours, I'll let you know. Enjoy your time out of town.

**Comment by crpeck** [comment]
I've updated the Dockerfile to reflect the new location of java, I ran docker-compose up in a pristine ubuntu VM and it ran fine. Good luck. Be sure to do a git pull.

**Comment by drupol** [comment]
It works pretty good now :-)

Now I have to figure out how to setup the SSL certificates properly. If you have any advice, feel free to let me know :-)

**Comment by crpeck** [comment]
Someone I work with is working on that I think. I'll ping him later this
week (he just started looking at that today). I take it you need a real
cert? What we do now is build the warfie and deploy it  in a standard VM,
the other person is looking at using Docker to deploy it.

**Comment by drupol** [comment]
Proxy authentification in CAS protocol only communicates in HTTPS.
However, I don't need real certs, I just would like to be able to use my own local certificates so I can test efficiently my CAS library with proxy authentification.

**Comment by drupol** [comment]
Fixed.
