### ISSUE TITLE
Unable to connect with /cas/login

### ISSUE THREAD

**Issue by drupol** [crpeck/cas-overlay-docker#3]
Hi,

When trying to connect to /cas/login for authentication, I get this message:

> The application you attempted to authenticate to is not authorized to use CAS. This usually indicates that the application is not registered with CAS, or its authorization policy defined in its registration record prevents it from leveraging CAS functionality, or it's malformed and unrecognized by CAS. Contact your CAS administrator to learn how you might register and integrate your application with CAS.

The URL of my client is: `https://ecasclient/` and the CAS server is `https://localhost:8443/cas`

What can I do to fix this ?

**Comment by crpeck** [comment]
You need to define services, at this point, you are into generic CAS, have
you looked at the CAS docs page https://apereo.github.io/cas/6.0.x/

**Comment by drupol** [comment]
Yes, i submitted a PR for that :)
