### ISSUE TITLE
Better way to include dependencies in the overlay

### ISSUE THREAD

**Issue by giovanism** [crpeck/cas-overlay-docker#8]
I need to copy different build.gradle to include the dependencies I want to enable on my CAS instance. Is there an easier/more reliable method to do this? Such as having the entire `cas-overlay-directory/` to override and modular `.gradle` files. Is it possible?

**Comment by crpeck** [comment]
I'm not sure how you would go about doing this, if you come up with a simple way to do that, please issue a pull request.

**Comment by giovanism** [comment]
Sorry, I can't.
